test_that("setup_global returns expected list", {
  out <- setup_global()
  expect_type(out, "list")
  expect_equal(out$N, 500)
  expect_equal(out$config, config)
  expect_equal(out$seed, 42)
  expect_equal(out$split_ratio, 0.70)
  expect_equal(out$H_grid, 1:length(config))
  expect_equal(out$model_ids, c("TTM", "TRUE"))
})
