test_that("main_moon runs end-to-end", {
  skip_on_cran()
  src_root <- testthat::test_path("..", "..")
  f_csv <- file.path(src_root, "results", "nll_halfmoon_seed007.csv")
  f_png <- file.path(src_root, "results", "halfmoon_panels_seed007.png")
  f_split <- file.path(src_root, "results", "splits_halfmoon2d_seed007.rds")
  unlink(c(f_csv, f_png, f_split))
  source(file.path(src_root, "main_moon.R"), chdir = TRUE)
  expect_true(file.exists(f_csv))
  expect_true(file.exists(f_png))
  df <- read.csv(f_csv, stringsAsFactors = FALSE)
  expect_equal(nrow(df), 5L)
  unlink(c(f_csv, f_png, f_split))
})
