name: Build and push Docker image

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/docker-image.yml
      - AGENTS.md
      - README.md
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      - name: Build image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/mde-r:latest .
      - name: Push image
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/mde-r:latest
